### ISSUE TITLE
Tailing equals is striped out in query string and params values

### ISSUE THREAD

**Issue by gmazzo** [googleapis/google-http-java-client#341] opened 2016-12-11 02:06 UTC
I'm hitting an ASP.Net server with a POST method and receiving a HTTP 302 response. The Location header is like the following:
http://server/page.aspx?id=IjLo+6Fft+IzHGYC4FzjQw==

The thing is that the library is stripping out the final = character, sending an incorrect request when handling the redirect to:
http://server/page.aspx?id=IjLo+6Fft+IzHGYC4FzjQw

As a workaround I have to handle the redirect manually.

The same issue is present if I set a POST form param value with a tailing = like:
param1=someValue=&param2=10

The library sends an incorrect request like:
param1=someValue&param2=10

This works well on any navigator I've tested it, it sounds like a bug to me. At least it should encode the parameter instead of stripping it out.

**Comment by stefanmendoza** [comment] 2017-05-29 10:41
Was able to verify this behavior by adding tests to [GenericUrlTest](https://github.com/google/google-http-java-client/blob/dev/google-http-client/src/test/java/com/google/api/client/http/GenericUrlTest.java):

`Test 1:`
```
  private static final String LONG_PATH_WITH_TRAILING_EQUALS = "http://bar/path/to/resource?a=b=";

  private static final List<String> LONG_PATH_WITH_TRAILING_EQUALS_PARTS = Arrays.asList("", "path", "to", "resource");

  public void testParse_longPathWithTrailingEquals() {
    GenericUrl url = new GenericUrl(LONG_PATH_WITH_TRAILING_EQUALS);
    assertEquals("http", url.getScheme());
    assertEquals("bar", url.getHost());
    assertEquals(LONG_PATH_WITH_TRAILING_EQUALS_PARTS, url.getPathParts());
    assertEquals("b=", url.getFirst("a"));
  }
```
`Test 1 Result:`
```
junit.framework.AssertionFailedError: 
Expected :b=
Actual   :b
```
`Test 2`
```
  private static final String SHORT_PATH_WITH_EQUAL_SIGN_IN_VALUE = "http://bar/path?a=b=cd";

  public void testParse_shortPathWithEqualSignInValue() {
    GenericUrl url = new GenericUrl(SHORT_PATH_WITH_EQUAL_SIGN_IN_VALUE);
    assertEquals("http", url.getScheme());
    assertEquals("bar", url.getHost());
    assertEquals(SHORT_PATH_PARTS, url.getPathParts());
    assertEquals("b=cd", url.getFirst("a"));
  }
```
`Test 2 Result`
```
junit.framework.AssertionFailedError: 
Expected :b=cd
Actual   :bcd
```

It seems that the issue is actually coming from the [UrlEncodedParser](https://github.com/google/google-http-java-client/blob/dev/google-http-client/src/main/java/com/google/api/client/http/UrlEncodedParser.java#L198-L201), specifically when the name and values are being read. If `readingName` is set to true, the `nameWriter` is used - else, the `valueWriter` is used. In the case where there is another character to read (in this case, '=') and it's not an '&', the following block is executed:

```
        case '=':
          // finished with name, now read value
          readingName = false;
          break;
```

Which doesn't write to the valueWriter. I was able to fix this by updating the block to write to `valueWriter` if the name is not being read. Need to read more into how to handle the building of the URL in this case (whether the '=' in the value should be encoded or not, but it seems like the might've fixed the issue.

**Comment by stefanmendoza** [comment] 2017-05-29 11:33
On second thought, I'm not sure if changing that block above fits within the expected behavior, since from what I can tell, the [UrlEncodedParser](https://github.com/google/google-http-java-client/blob/dev/google-http-client/src/main/java/com/google/api/client/http/UrlEncodedParser.java) class is expecting an encoded URL. This functionality is already tested for building the URL [here](https://github.com/google/google-http-java-client/blob/dev/google-http-client/src/test/java/com/google/api/client/http/GenericUrlTest.java#L178-L179) and parsing the URL [here](https://github.com/google/google-http-java-client/blob/dev/google-http-client/src/test/java/com/google/api/client/http/GenericUrlTest.java#L227).

**Comment by ajaaym** [comment] 2018-12-04 21:05
This works fine in latest version. Closing this for now. Please reopen if this is still an issue.

**Closed by ajaaym** 2018-12-04 21:05 UTC
Labels: :rotating_light:, priority: p2, type: bug
