### ISSUE TITLE
HttpContent is encoded two times when posting data

### ISSUE THREAD

**Issue by chingor13** [googleapis/google-http-java-client#648] opened 2019-05-24 17:10 UTC
The resulting request is correctly encoded once, but we are encoding an extra time when we calculate the content length.

**Comment by sduskis** [comment] 2019-05-29 19:21
This is a duplicate of #283.

**Comment by chingor13** [comment] 2019-06-03 23:11
It turns out this is non-trivial to fix. The issue is that for some transport adapters, we have to set the Content-Length header before we start streaming the content. This means that we must count the bytes before we send them. We don't want to cache the encoded content in memory as it defeats the purpose of streaming the content and could cause memory spikes in the application. We don't want to write to a temporary file as there may be file system issues/restrictions (like on GAE) that we cannot necessarily plan for.

**Comment by codyoss** [comment] 2019-10-15 15:36
@chingor13 do we have more details on this one? Such as what is being affected? Or is there a finite list of Transport Adapters that need the `Content-Length` set?

**Comment by codyoss** [comment] 2019-12-09 19:53
I will take a stab at this.

**Closed** 2019-12-17 17:20 UTC
Labels: :rotating_light:, priority: p1, type: bug
