### ISSUE TITLE
Documentation for GSON extension should call out limitations

### ISSUE THREAD

**Issue by GuyPaddock** [googleapis/google-http-java-client#338] opened 2016-11-06 16:46 UTC
I have used GSON extensively in other applications (with Android and in Spring applications), but am new to Google HTTP client (previously used Apache's HTTP client).

I just spent several hours stepping through the innards of the Google HTTP client trying to figure out why classes that GSON can natively marshall are not marshallable when using `JsonObjectParser` with GSON under the hood. It turns out that, as several other issues and mailing list posts seem to confirm, none of GSON's low-level, native JSON parsing or object reflection capabilities are used. This means that you cannot use GSON's annotations and must specify a `@Key` annotation on all fields.

If that's the case, I have two questions:
- What's the point in using GSON at all, if the HTTP client's core code is doing all the actual JSON parsing?
- Why isn't there any documentation to spell out that `JsonObjectParser` + GSON is not as flexible as just using GSON directly?

**Comment by sduskis** [comment] 2018-12-06 15:59
@chingor13, do you have any context on this issue?  If not, please close it due to staleness.

**Comment by chingor13** [comment] 2018-12-06 16:13
The google-http-client-gson (and all the other parsing artifacts) are there to allow swappable JSON implementations around the `GenericJson` provided by `google-http-client`. As you point out, you have to use the `@Key` annotations which is by design.

If you are trying to use this library outside of the scope of `google-api-client`, you may have more customization options if you use a low-level HTTP client + your parser of choice. 

The `google-http-client` was designed to provide an standard interface over several low-level HTTP clients and parsers. By doing so, you inherently lose some of the features of the low-level libraries.

**Closed by chingor13** 2018-12-06 16:13 UTC
Labels: type: docs
